# Generated by Django 2.2.4 on 2019-08-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moremodel', '0002_auto_20190817_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='artirelationico',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduct',
            field=models.CharField(default='', max_length=255),
        ),
    ]
